variable "vpcmod_region" {}
variable "vpcmod_clientname" {}
variable "vpcmod_aws_vpc_cidr" {}
variable "vpcmod_aws_pub_a_subnet" {}
variable "vpcmod_aws_pub_b_subnet" {}
variable "vpcmod_aws_pub_c_subnet" {}
variable "vpcmod_aws_priv_a_subnet" {}
variable "vpcmod_aws_priv_b_subnet" {}
variable "vpcmod_aws_priv_c_subnet" {}
variable "vpcmod_aws_dmz_a_subnet" {}
variable "vpcmod_aws_dmz_b_subnet" {}
variable "vpcmod_aws_dmz_c_subnet" {}
variable "vpcmod_aws_az_a" {}
variable "vpcmod_aws_az_b" {}
variable "vpcmod_aws_az_c" {}
variable "vpcmod_aws_nat_ami" {}
variable "vpcmod_key_name" {}
variable "vpcmod_stack_name" {}
variable "vpcmod_env_name" {}
variable "vpcmod_creator" {}
